project:
  type: book
  output-dir: docs

book:
  title: "Git y GitHub con R"
  reader-mode: true
  site-url: https://davidrsch.github.io/hggh4r-es/

  page-footer:
    left: |
      <strong>“Git y GitHub con ”</strong> fue escrito por Jenny Bryan, profesores asistentes de STAT 545 y Jim Hester.
    right: |
      Este libro se hizo usando <a href="https://quarto.org/">Quarto</a>.
  favicon: logo.png
  author:
    - name: Jenny Bryan
    - name: STAT 545 TAs
    - name: Jim Hester
  search: true
  sidebar:
    pinned: true
    tools:
      - icon: github
        menu:
          - text: Original
            url: https://github.com/jennybc/happy-git-with-r
          - text: Traducción
            url: https://github.com/davidrsch/hggh4r-es
  chapters:
    - index.qmd
    - overview.qmd
    - contributors.qmd
    - workshops.qmd
    - part: "Instalación"
      chapters:
        - install-intro.qmd
        - install-github-acct.qmd
        - install-r-rstudio.qmd
        - install-git.qmd
        - install-introduce-self-git.qmd
        - install-git-client.qmd
    - part: "Conectar Git, GitHub, RStudio"
      chapters:
        - connect-intro.qmd
        - connect-https-pat.qmd
        - connect-ssh-keys.qmd
        - connect-git-github.qmd
        - connect-rstudio-git-github.qmd
        - connect-can-rstudio-use-git.qmd
        - connect-troubleshooting.qmd
    - part: "Primeras victorias en GitHub"
      chapters:
        - usage-intro.qmd
        - usage-new-project-github-first.qmd
        - usage-existing-project-github-first.qmd
        - usage-existing-project-github-last.qmd
        - usage-rmd-and-github.qmd
        - usage-r-script-and-github.qmd
    - part: "Fundamentos de Git"
      chapters:
        - git-intro.qmd
        - git-basics.qmd
        - git-commands.qmd
        - git-branches.qmd
        - git-remotes.qmd
        - git-refs.qmd
    - part: "Configuraciones de remotos"
      chapters:
        - remote-setups-intro.qmd
        - remote-setups-common.qmd
        - remote-setups-equivocal.qmd
    - part: "Flujos de trabajo diarios"
      chapters:
        - workflows-intro.qmd
        - workflows-repeated-amend.qmd
        - workflows-push-rejected.qmd
        - workflows-pull.qmd
        - workflows-see-the-past.qmd
        - workflows-fork-and-clone.qmd
        - workflows-upstream-changes-into-fork.qmd
        - workflows-explore-extend-pull-request.qmd
        - workflows-make-github-repo-browsable.qmd
    - part: "Indicaciones de actividad"
      chapters:
        - prompt-clone.qmd
        - prompt-fork-pr-bingo.qmd
        - prompt-burn-it-all-down.qmd
        - prompt-practice-resets.qmd
        - prompt-search-github.qmd
    - part: "Notas"
      chapters:
        - notes-intro.qmd
        - notes-classroom-overview.qmd
        - notes-ideas.qmd
        # - notes-bookdown-cheat-sheet.qmd
  appendices:
    - shell.qmd
    - comic-relief.qmd
    - resources.qmd
    - references.qmd
lang: es


format:
  html:
    theme:
      - cosmo
      - hgitwithr.scss
    code-link: true
    bibliography: [book.bib, packages.bib]
    biblio-style: apalike
    link-citations: yes
    author-meta: "Jenny Bryan, profesores asistentes de STAT 545 y Jim Hester"
    callout-appearance: simple
    include-in-header: [ddrsch_script_header.html]
    include-after-body: [ddrsch_script.html]

editor: visual
